### ISSUE TITLE
could not make it working with rebble

### ISSUE THREAD

**Issue by niran-manandhar** [PanicMan/Pebble-b00bs#1]
any one tried this recently?  trying to revive my pebble

**Comment by PanicMan** [comment]
Just copy the pbw file to your phone and open it, should be done with pebble app.
But I anyway not working on this anymore, as I don't have a pebble anymore...

**Comment by niran-manandhar** [comment]
![image](https://user-images.githubusercontent.com/11488943/108705093-83be9380-7515-11eb-8d40-6cc73223ed33.png)
got,  as unsupported  watchface.
